# Time/Date Sensor
- platform: time_date
  monitored_conditions:
    - time
    - date


# hide_entity: true
  # scan_interval: 30000
  # sensors:
    # day_after_tomorrow:
      # friendly_name: 'Day After Tomorrow'
      # value_template: >-
        # {{ (as_timestamp(now()) + 172800) | timestamp_custom("%a") }}

# - platform: template
  # hide_entity: true
  # scan_interval: 30000
  # sensors:
    # day_after_that:
      # friendly_name: 'Day After That'
      # value_template: >-
        # {{ (as_timestamp(now()) + 259200) | timestamp_custom("%a") }}

 #sensor 3
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

#System Monitor
- platform: systemmonitor
  # name: 'System Monitor'
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot
    - type: processor_use
    - type: load_1m

## Google Geocode Tracker  ##
# - platform: google_geocode
  # name: YourFriendCaspian
  # origin: device_tracker.yfc_oneplustech
  # options: street, city, postal_code
  # display_zone: true
  # gravatar: yourfriendcaspian@gmail.com

## Office Sensor  ##
# - platform: dht
  # name: 'Office'
  # sensor: DHT22
  # pin: 05
  # temperature_offset: 2.1
  # humidity_offset: -3.2
  # monitored_conditions:
    # - temperature
    # - humidity

- platform: bme280
  name: Ambient
  i2c_address: 0x76
  operation_mode: 2  # forced mode
  time_standby: 5
  oversampling_temperature: 4
  oversampling_pressure: 4
  oversampling_humidity: 4
  delta_temperature: -0.5
  monitored_conditions:
    - temperature
    - humidity
    - pressure
  scan_interval: 40

## The Luv Shack  ##
- platform: mqtt
  name: 'Livingroom Temp'
  state_topic: 'luvshack/temperature'
  unit_of_measurement: '°F'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  name: 'Livingroom Humidity'
  state_topic: 'luvshack/humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

## Studio  ##
- platform: mqtt
  name: 'Studio Temp'
  state_topic: 'yfc/Studio/Temp'
  unit_of_measurement: '°F'
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  name: 'Studio Humidity'
  state_topic: 'yfc/Studio/Humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity | round(1) }}'

  # - platform: mqtt
  # name: 'Luv Shack Motion'
  # state_topic: 'luvshack/pisensor'
  # value_template: '{{ value_json.motion }}'

 ###Bruh MultiSensor####

- platform: mqtt
  name: 'Humidity'
  state_topic: 'bruh/livingroom'
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  name: 'Lights'
  state_topic: 'bruh/livingroom'
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  name: 'Temp'
  state_topic: 'bruh/livingroom'
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  name: 'Real Feel'
  state_topic: 'bruh/livingroom'
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  name: 'Motion'
  state_topic: 'bruh/livingroom'
  value_template: '{{ value_json.motion }}'

#####Basement Multisensor w/ Door Sensor######
- platform: mqtt
  name: 'Basement Temp'
  state_topic: '0B4F3D/sensor/temperature'
  unit_of_measurement: '°F'
  availability_topic: '0B4F3D/status'
  payload_available: 'online'
  payload_not_available: 'offline'

- platform: mqtt
  name: 'Basement Humidity'
  state_topic: '0B4F3D/sensor/humidity'
  unit_of_measurement: '%'
  availability_topic: '0B4F3D/status'
  payload_available: 'online'
  payload_not_available: 'offline'

- platform: mqtt
  name: 'Basement Lights'
  state_topic: '0B4F3D/sensor/lux'
  unit_of_measurement: 'lux'
  availability_topic: '0B4F3D/status'
  payload_available: 'online'
  payload_not_available: 'offline'

## ShadyGateway ##

- platform: mqtt
  name: "Temp"
  state_topic: "shadyoak/ShadyGateway/DHTtoMQTT/dht1/temp"
  unit_of_measurement: "°F"
  value_template: '{{ value | round(2)  }}'

- platform: mqtt
  name: "Humidity"
  state_topic: "shadyoak/ShadyGateway/DHTtoMQTT/dht1/hum"
  unit_of_measurement: "%"
  value_template: '{{ value | round(2)  }}'

# - platform: template
  # mqtt_real_feel:
  # friendly_name: "Real Feel"
  # value_template: '{{ (((-42.379 + (2.04901523*(((states.mqtt_rf_temperature.state|float)*1.8)+32)) + (10.14333127*(states.mqtt_rf_humidity.state|float)) - (0.22475541*(((states.mqtt_rf_temperature.state|float)*1.8)+32)*(states.mqtt_rf_humidity.state|float)) - (6.83783 * (10**(-3))*((((states.mqtt_rf_temperature.state|float)*1.8)+32)**2)) - (5.481717 * (10**(-2))*((states.mqtt_rf_humidity.state|float)**2)) + (1.22874 * (10**(-3))*((((states.mqtt_rf_temperature.state|float)*1.8)+32)**2*(states.mqtt_rf_humidity.state|float))) + (8.5282 * (10**(-4))*((((states.mqtt_rf_temperature.state|float)*1.8)+32)*(states.mqtt_rf_humidity.state|float)**2)) - (1.99 * (10**(-6))*((((states.mqtt_rf_temperature.state|float)*1.8)+32)**2)*((states.mqtt_rf_humidity.state|float)**2)))-32)/1.8)|round(2) }}'
  # unit_of_measurement: "°F"

        
## Weather ##

- platform: moon

- platform: wunderground
  api_key: !secret wunderground_api
  latitude: !secret lat
  longitude: !secret long
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    # - temp_high_record_f
    - temp_high_1d_f
    - temp_f
    - feelslike_f
    - location
    - temp_low_1d_f
    # - temp_low_record_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
