- platform: moon

- platform: yr
  name: YR.no Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: wunderground
  api_key: !secret wunderground_api
  latitude: 41.396418
  longitude: -70.542851
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - temp_high_record_f
    - temp_high_1d_f
    - temp_f
    - feelslike_f
    - location
    - temp_low_1d_f
    - temp_low_record_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts